// <auto-generated />
using System;
using CargoPulse.Fleet.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CargoPulse.Fleet.Infrastructure.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    partial class FleetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CargoPulse.Fleet.Domain.Aggregates.AssigmentAggregates.AssignmentStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualArrivalTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualDepartureTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EstimatedArrivalTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RouteStopId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScheduledStayDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("RouteStopId");

                    b.ToTable("AssignmentStops", (string)null);
                });

            modelBuilder.Entity("CargoPulse.Fleet.Domain.Aggregates.DriverAggregates.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("CargoPulse.Fleet.Domain.Aggregates.RouteAggregates.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("EstimatedDistanceKm")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("CargoPulse.Fleet.Domain.Aggregates.RouteAggregates.RouteStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<int>("StopSequence")
                        .HasColumnType("integer");

                    b.Property<string>("StopType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteStops", (string)null);
                });

            modelBuilder.Entity("CargoPulse.Fleet.Domain.Aggregates.VehicleAggregates.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CapacityTonnage")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MaxSpeedLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("CargoPulse.Fleet.Domain.Aggregates.VehicleAssigmentAggregates.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CargoTonnage")
                        .HasColumnType("double precision");

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Assignments", (string)null);
                });

            modelBuilder.Entity("CargoPulse.Fleet.Domain.HubAggregates.Hub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Hubs", (string)null);
                });

            modelBuilder.Entity("CargoPulse.Fleet.Domain.HubAggregates.ParkingSpace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HubId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OccupiedByVehicleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("OccupiedFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OccupiedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpaceDesignation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("HubId");

                    b.HasIndex("OccupiedByVehicleId");

                    b.ToTable("ParkingSpaces", (string)null);
                });

            modelBuilder.Entity("CargoPulse.Fleet.Domain.Aggregates.AssigmentAggregates.AssignmentStop", b =>
                {
                    b.HasOne("CargoPulse.Fleet.Domain.Aggregates.VehicleAssigmentAggregates.Assignment", null)
                        .WithMany("Stops")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CargoPulse.Fleet.Domain.Aggregates.RouteAggregates.RouteStop", null)
                        .WithMany()
                        .HasForeignKey("RouteStopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CargoPulse.Fleet.Domain.Aggregates.DriverAggregates.Driver", b =>
                {
                    b.OwnsOne("CargoPulse.Fleet.Domain.Aggregates.VehicleAssigmentAggregates.Destination", "HomeBaseLocation", b1 =>
                        {
                            b1.Property<Guid>("DriverId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("HubId")
                                .HasColumnType("uuid")
                                .HasColumnName("HomeHubId");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("HomeLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("HomeLongitude");

                            b1.HasKey("DriverId");

                            b1.ToTable("Drivers");

                            b1.WithOwner()
                                .HasForeignKey("DriverId");
                        });

                    b.Navigation("HomeBaseLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("CargoPulse.Fleet.Domain.Aggregates.RouteAggregates.RouteStop", b =>
                {
                    b.HasOne("CargoPulse.Fleet.Domain.Aggregates.RouteAggregates.Route", null)
                        .WithMany("Stops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CargoPulse.Fleet.Domain.Aggregates.VehicleAssigmentAggregates.Destination", "Location", b1 =>
                        {
                            b1.Property<Guid>("RouteStopId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("HubId")
                                .HasColumnType("uuid")
                                .HasColumnName("HubId");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Longitude");

                            b1.HasKey("RouteStopId");

                            b1.ToTable("RouteStops");

                            b1.WithOwner()
                                .HasForeignKey("RouteStopId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("CargoPulse.Fleet.Domain.Aggregates.VehicleAggregates.Vehicle", b =>
                {
                    b.OwnsOne("CargoPulse.Fleet.Domain.Aggregates.VehicleAssigmentAggregates.Destination", "CurrentLocation", b1 =>
                        {
                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("HubId")
                                .HasColumnType("uuid")
                                .HasColumnName("CurrentHubId");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("CurrentLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("CurrentLongitude");

                            b1.HasKey("VehicleId");

                            b1.ToTable("Vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.Navigation("CurrentLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("CargoPulse.Fleet.Domain.Aggregates.VehicleAssigmentAggregates.Assignment", b =>
                {
                    b.HasOne("CargoPulse.Fleet.Domain.Aggregates.DriverAggregates.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CargoPulse.Fleet.Domain.Aggregates.RouteAggregates.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CargoPulse.Fleet.Domain.Aggregates.VehicleAggregates.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Route");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CargoPulse.Fleet.Domain.HubAggregates.ParkingSpace", b =>
                {
                    b.HasOne("CargoPulse.Fleet.Domain.HubAggregates.Hub", null)
                        .WithMany("ParkingSpaces")
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CargoPulse.Fleet.Domain.Aggregates.VehicleAggregates.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("OccupiedByVehicleId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CargoPulse.Fleet.Domain.Aggregates.RouteAggregates.Route", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("CargoPulse.Fleet.Domain.Aggregates.VehicleAssigmentAggregates.Assignment", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("CargoPulse.Fleet.Domain.HubAggregates.Hub", b =>
                {
                    b.Navigation("ParkingSpaces");
                });
#pragma warning restore 612, 618
        }
    }
}
